production:
  domain: "deployment_user@staging.mydomain.com"
  deploy_to: "/path/to/where/i/deploy/staging.mydomain.com"
  repository: "https://github.com/username/project.git"
  branch: "master"

staging:
  domain: "deployment_user@staging.mydomain.com"
  deploy_to: "/path/to/where/i/deploy/staging.mydomain.com"
  repository: "https://github.com/username/project.git"
  branch: "staging"